services:
  django:
    container_name: simple_lms
    build: .
    # depends_on untuk memastikan DB mulai duluan
    depends_on:
      - postgres 
    # command agar kontainer tetap hidup (IDLE)
    command: sleep infinity 
    volumes:
      - ./code:/code
    ports:
      - "8001:8000"
  postgres:
    container_name: simple_db
    image: postgres:latest
    environment:
      POSTGRES_DB: simple_lms
      POSTGRES_USER: simple_user
      POSTGRES_PASSWORD: simple_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5532:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata